# -*- coding: utf-8 -*-
"""protocolo Árvores de Decisão.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y896L69qezLKjjMxdXBk6qNnDBl5jSS7
"""

# 1
from sklearn import tree
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt

X, y = load_iris(return_X_y = True)
# Mexer aqui, por default é None
clf = tree.DecisionTreeClassifier(max_depth=None)
clf = clf.fit(X, y)
tree.plot_tree(clf)
plt.show()

# 2
from sklearn import tree, metrics
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

x_values, y_values = load_iris(return_X_y = True)
x_train, x_test, y_train, y_test = train_test_split(x_values, y_values, test_size=0.3, random_state=0)

clf = tree.DecisionTreeClassifier()
clf = clf.fit(x_train, y_train)

predict = clf.predict(x_test)

print("Accuracy:", metrics.accuracy_score(y_test, predict))

# 3
from sklearn import tree, metrics
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt

x_values = []
y_values = []

def ReadCSV():
  global x_values, y_values
  file_path = "/content/pizza.csv"
  base = pd.read_csv(file_path)
  
  x_values = base.iloc[:,0].values
  x_values = x_values.reshape(-1,1)
    
  y_values = base.iloc[:,1].values
  y_values = y_values.reshape(-1,1)

def Regression():
  global x_values, y_values

  x_train, x_test, y_train, y_test = train_test_split(x_values, y_values, test_size=0.3, random_state=0)
  # Mexer no max_depth
  regressor = tree.DecisionTreeRegressor()
  regressor.fit(x_train, y_train)

  predict = regressor.predict(x_test)
  mae = metrics.mean_absolute_error(y_test, predict)
  print('MAE: %f' %(mae))
  plt.scatter(x_values, y_values)
  plt.plot(x_test, predict, color='red')
  plt.title('Regressão Pizza')
  plt.xlabel('Annual Fee')
  plt.ylabel('Startup Cost')
  plt.show()

ReadCSV()
Regression()

# 4
from sklearn import tree, metrics, linear_model
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt

x_values = []
y_values = []

def ReadCSV():
  global x_values, y_values
  file_path = "/content/pizza.csv"
  base = pd.read_csv(file_path)
  
  x_values = base.iloc[:,0].values
  x_values = x_values.reshape(-1,1)
    
  y_values = base.iloc[:,1].values
  y_values = y_values.reshape(-1,1)

def DecisionTreeRegression():
  global x_values, y_values

  x_train, x_test, y_train, y_test = train_test_split(x_values, y_values, test_size=0.3, random_state=0)
  # Mexer no max_depth
  regressor = tree.DecisionTreeRegressor(max_depth=5)
  regressor.fit(x_train, y_train)

  predict = regressor.predict(x_test)
  mae = metrics.mean_absolute_error(y_test, predict)

  print('MAE: %f' %(mae))
  plt.scatter(x_values, y_values)
  plt.plot(x_test, predict, color='red')
  

def LinearRegression():
  global x_values, y_values
  x_train, x_test, y_train, y_test = train_test_split(x_values, y_values, test_size=0.3, random_state=0)
  regressor = linear_model.LinearRegression()
  regressor.fit(x_train, y_train)

  predict = regressor.predict(x_test)
  mae = metrics.mean_absolute_error(y_test, predict)

  print('MAE: %f' %(mae))
  plt.plot(x_test, predict, color='green')
  plt.title('Regressões Pizza')
  plt.xlabel('Annual Fee')
  plt.ylabel('Startup Cost')
  plt.show()

ReadCSV()
DecisionTreeRegression()
LinearRegression()